const fs=require('fs'),vm=require('vm'),path=require('path'),assert=require('assert');
function read(file,context={}) {vm.createContext(context);vm.runInContext(fs.readFileSync(path.resolve(__dirname,file),'utf8').replace(/^\.(pragma|import).*$/gm,''),context);return context;}
const h=read('../../HarmonyAssistant/Harmony.js'),t=read('../../HarmonyAssistant/Timeline.js',{Harmony:h}),r=read('../Rules.js',{Harmony:h,Timeline:t});
let passed=0;
function test(name,body){body();passed++;console.log('PASS '+name);}
function note(pitch,tick=0,end=960,track=0,tpc){return {id:`${tick}:${track}:${pitch}`,pitch,tick,attackTick:tick,end,logicalEnd:end,track,index:0,tpc:tpc===undefined?({0:14,1:21,2:16,3:9,4:18,5:13,6:20,7:15,8:8,9:17,10:12,11:19})[pitch%12]:tpc,measure:1,beat:1+tick/480,onSeconds:tick/960,endSeconds:end/960};}
function data(notes,pedals=[]){return {notes,pedals,hands:[],harmonies:[],meters:[{tick:0,end:7680,measure:1,denominator:4}],scope:{start:0,end:7680,firstTrack:0,endTrack:8}};}
function check(notes,config=r.defaults(),pedals=[]){return r.run(data(notes,pedals),config).issues;}
function codes(issues){return issues.map(i=>i.code);}
test('read-only same-pitch voices retained',()=>{let d=data([note(60,0,480,0),note(60,0,480,4)]),before=JSON.stringify(d),state=r.run(d,r.defaults());assert.equal(state.roles.length,2);assert.equal(JSON.stringify(d),before);});
test('spelled pure fifth to diminished fifth is not parallel',()=>{let ns=[note(60,0,480,4),note(67,0,480,0),note(62,480,960,4),note(68,480,960,0,8)];assert(!codes(check(ns)).includes('parallel-5'));});
test('parallel fifth in either track order',()=>{let ns=[note(60,0,480,4),note(67,0,480,0),note(62,480,960,4),note(69,480,960,0)];assert(codes(check(ns)).includes('parallel-5'));});
test('contrary motion does not create parallels',()=>{let ns=[note(60,0,480,4),note(67,0,480,0),note(58,480,960,4),note(69,480,960,0)];assert(!codes(check(ns)).some(c=>/^parallel/.test(c)));});
test('polyphonic automatic voice is uncertain',()=>{let state=r.run(data([note(60),note(64),note(67)]),r.defaults());assert(state.roles[0].uncertain);assert(!state.roles[0].independent);});
test('doubled voice explicitly disabled',()=>{let c=r.defaults();c.roles={'4':{independent:false}};let ns=[note(60,0,480,4),note(72,0,480,0),note(62,480,960,4),note(74,480,960,0)];assert(!codes(check(ns,c)).includes('parallel-8'));});
test('passing nonchord tone not called a color error',()=>{let c=r.defaults();c.chords=[{start:0,end:2000,root:0,definition:0,source:'局部指定'}];assert(!codes(check([note(64,0,480),note(66,480,960),note(67,960,1440)],c)).includes('chord-color'));});
test('suspension resolves by step',()=>{let c=r.defaults();c.chords=[{start:480,end:2000,root:0,definition:0,source:'局部指定'}];assert(!codes(check([note(71,0,960),note(72,960,1440)],c)).includes('chord-color'));});
test('extended chord tensions do not become automatic errors',()=>{let c=r.defaults();c.chords=[{start:0,end:2000,root:0,definition:22,source:'局部指定'}];assert(!codes(check([note(60),note(64),note(70),note(74),note(81)],c)).includes('chord-color'));});
test('user chord sustained semitone conflict requires review',()=>{let c=r.defaults();c.chords=[{start:0,end:2000,root:0,definition:0,source:'局部指定'}];assert(codes(check([note(61,0,1440)],c)).includes('chord-color'));});
test('ambiguity suppresses definite chord warnings',()=>{let c=r.defaults();let s=r.create(data([note(61)]),c,[{start:0,end:2000,part:0,root:0,definition:0,source:'导入',alternatives:[{root:1}]}]);while(!r.step(s,20)){}assert(!codes(s.issues).includes('chord-color'));});
test('white endpoints allow major tenth',()=>{assert(!codes(check([note(60),note(76)])).includes('span-right'));assert(codes(check([note(61),note(77)])).includes('span-right'));});
test('major ninth is comfortable',()=>{assert(!codes(check([note(60),note(74)])).includes('comfort-right'));});
test('equal span different transition context',()=>{let stationary=[note(60,0,120),note(74,0,120),note(60,120,240),note(74,120,240)];let moving=[note(60,0,120),note(74,0,120),note(84,120,240),note(98,120,240)];assert(!codes(check(stationary)).includes('transition-right'));assert(codes(check(moving)).includes('transition-right'));});
test('pedal release changes span explanation',()=>{let ns=[note(60),note(79)],plain=check(ns),under=check(ns,r.defaults(),[{tick:0,end:1500,firstTrack:0,endTrack:8}]);assert.equal(plain.find(i=>i.code==='span-right').severity,'需核查');assert.equal(under.find(i=>i.code==='span-right').severity,'注意');});
test('six different keys produce burden but unison does not',()=>{assert(codes(check([60,62,64,65,67,69].map(p=>note(p)))).includes('keys-right'));assert(!codes(check(Array.from({length:6},()=>note(60)))).includes('keys-right'));});
test('tie across bar appears once logically',()=>{let n=note(60,0,3840);let continuation={...n,tick:1920,tieBack:true,id:'1920:0:0'};let s=r.run(data([n,continuation]),r.defaults());assert.equal(s.byTick[0].length,1);});
test('unpaired native hand ranges need correction',()=>{let d=data([note(60),note(79)]);d.hands=[{tick:0,track:0,index:-1,left:true,bracket:false}];let s=r.run(d,r.defaults());assert(codes(s.issues).includes('span-left'));});
test('ignored issue remains absent',()=>{let ns=[note(60),note(79)],c=r.defaults(),first=check(ns,c);c.ignored=[first.find(i=>i.code==='span-right').id];assert(!codes(check(ns,c)).includes('span-right'));});
test('one pedal keeps one stable chord across bar',()=>{let ns=[note(36,0,480,4),note(52,0,480,4),note(55,0,480,4),note(74,1920,2400,0)];let s=r.run(data(ns,[{tick:0,end:3840,firstTrack:0,endTrack:8}]),r.defaults());assert.equal(s.regions.length,1);assert.equal(s.regions[0].root,0);});
test('automatic octave doubling not claimed independent',()=>{let ns=[note(60,0,480,4),note(72,0,480,0),note(62,480,960,4),note(74,480,960,0)];assert(!codes(check(ns)).includes('parallel-8'));});
test('worker bundle uses the exact shared modules',()=>{const source=r.workerBundle({harmony:fs.readFileSync(path.resolve(__dirname,'../../HarmonyAssistant/Harmony.js'),'utf8'),timeline:fs.readFileSync(path.resolve(__dirname,'../../HarmonyAssistant/Timeline.js'),'utf8'),rules:fs.readFileSync(path.resolve(__dirname,'../Rules.js'),'utf8')});let output=vm.runInNewContext(source,{input:{data:data([note(60),note(79)]),config:r.defaults(),imported:[]}});assert(codes(output.issues).includes('span-right'));});
test('conflicting hand symbols remain uncertain, not an impossible span',()=>{let d=data([note(60),note(79)]);d.hands=[{tick:0,track:0,index:-1,left:true},{tick:0,track:0,index:-1,left:false}];let c=codes(r.run(d,r.defaults()).issues);assert(c.includes('hand-uncertain'));assert(!c.includes('span-left')&&!c.includes('span-right'));});
test('unpaired bracket never implies an unlimited hand range',()=>{let d=data([note(60),note(79)]);d.hands=[{tick:0,track:0,index:-1,left:true,bracket:true}];assert(codes(r.run(d,r.defaults()).issues).includes('hand-uncertain'));});
test('Jazz defaults and explicit parallel rule override',()=>{let ns=[note(60,0,480,4),note(67,0,480,0),note(62,480,960,4),note(69,480,960,0)],c=r.defaults();c.style=2;assert(!codes(check(ns,c)).includes('parallel-5'));c.ruleOverrides.parallel=true;assert(codes(check(ns,c)).includes('parallel-5'));});
test('logical tie uses the origin index even when chord ordering changes',()=>{let n=note(60,0,3840);n.attackIndex=1;n.index=1;let continuation={...n,tick:1920,index:0,tieBack:true,id:'1920:0:0'};let s=r.run(data([n,continuation]),r.defaults());assert.equal(s.byTick[0].length,1);});
test('leading-tone guidance requires an explicitly confirmed tonic',()=>{let ns=[note(71,0,480),note(67,480,960)],c=r.defaults();assert(!codes(check(ns,c)).includes('resolution'));c.tonic=0;assert(codes(check(ns,c)).includes('resolution'));});
console.log(`${passed} rule tests passed`);
